version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    docker:
      - image: uodna/qmk_firmware:circleci
    steps:
      - *attach_workspace
      - checkout
      - run: make iris:uodna-osx-ansi
      - run: make crkbd:uodna
      - run: mv .build /tmp/workspace/build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            unset  AWS_SESSION_TOKEN
            temp_role=$(aws sts assume-role \
                                --role-arn "arn:aws:iam::436693060040:role/circleci_qmk_role" \
                                --role-session-name "circleci_qmk")
            export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
            export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
            export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
            aws s3 cp build/*.hex s3://uodna0-prod1-qmk/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci
